import * as iohook from 'uiohook-napi';

const UNSUPPORTED_KEY = "UNSUPPORTED KEY";

export function keyFromKeycode(keycode: number): string {
    switch (keycode) {
        case iohook.UiohookKey.Backspace:
            return "backspace";
        case iohook.UiohookKey.Tab:
            return "tab";
        case iohook.UiohookKey.Enter:
            return "enter";
        case iohook.UiohookKey.CapsLock:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.Escape:
            return "escape";
        case iohook.UiohookKey.Space:
            return "space";
        case iohook.UiohookKey.PageUp:
            return "pageup";
        case iohook.UiohookKey.PageDown:
            return "pagedown";
        case iohook.UiohookKey.End:
            return "end";
        case iohook.UiohookKey.Home:
            return "home";
        case iohook.UiohookKey.ArrowLeft:
            return "left";
        case iohook.UiohookKey.ArrowUp:
            return "up";
        case iohook.UiohookKey.ArrowRight:
            return "right";
        case iohook.UiohookKey.ArrowDown:
            return "down";
        case iohook.UiohookKey.Insert:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.Delete:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey[0]:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey[1]:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey[2]:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey[3]:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey[4]:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey[5]:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey[6]:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey[7]:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey[8]:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey[9]:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.A:
            return "a";
        case iohook.UiohookKey.B:
            return "b";
        case iohook.UiohookKey.C:
            return "c";
        case iohook.UiohookKey.D:
            return "d";
        case iohook.UiohookKey.E:
            return "e";
        case iohook.UiohookKey.F:
            return "f";
        case iohook.UiohookKey.G:
            return "g";
        case iohook.UiohookKey.H:
            return "h";
        case iohook.UiohookKey.I:
            return "i";
        case iohook.UiohookKey.J:
            return "j";
        case iohook.UiohookKey.K:
            return "k";
        case iohook.UiohookKey.L:
            return "l";
        case iohook.UiohookKey.M:
            return "m";
        case iohook.UiohookKey.N:
            return "n";
        case iohook.UiohookKey.O:
            return "o";
        case iohook.UiohookKey.P:
            return "p";
        case iohook.UiohookKey.Q:
            return "q";
        case iohook.UiohookKey.R:
            return "r";
        case iohook.UiohookKey.S:
            return "s";
        case iohook.UiohookKey.T:
            return "t";
        case iohook.UiohookKey.U:
            return "u";
        case iohook.UiohookKey.V:
            return "v";
        case iohook.UiohookKey.W:
            return "w";
        case iohook.UiohookKey.X:
            return "x";
        case iohook.UiohookKey.Y:
            return "y";
        case iohook.UiohookKey.Z:
            return "z";
        case iohook.UiohookKey.Numpad0:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.Numpad1:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.Numpad2:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.Numpad3:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.Numpad4:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.Numpad5:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.Numpad6:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.Numpad7:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.Numpad8:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.Numpad9:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.NumpadMultiply:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.NumpadAdd:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.NumpadSubtract:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.NumpadDecimal:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.NumpadDivide:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.NumpadEnd:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.NumpadArrowDown:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.NumpadPageDown:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.NumpadArrowLeft:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.NumpadArrowRight:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.NumpadHome:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.NumpadArrowUp:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.NumpadPageUp:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.NumpadInsert:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.NumpadDelete:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.F1:
            return "f1";
        case iohook.UiohookKey.F2:
            return "f2";
        case iohook.UiohookKey.F3:
            return "f3";
        case iohook.UiohookKey.F4:
            return "f4";
        case iohook.UiohookKey.F5:
            return "f5";
        case iohook.UiohookKey.F6:
            return "f6";
        case iohook.UiohookKey.F7:
            return "f7";
        case iohook.UiohookKey.F8:
            return "f8";
        case iohook.UiohookKey.F9:
            return "f9";
        case iohook.UiohookKey.F10:
            return "f10";
        case iohook.UiohookKey.F11:
            return "f11";
        case iohook.UiohookKey.F12:
            return "f12";
        case iohook.UiohookKey.F13:
            return "f13";
        case iohook.UiohookKey.F14:
            return "f14";
        case iohook.UiohookKey.F15:
            return "f15";
        case iohook.UiohookKey.F16:
            return "f16";
        case iohook.UiohookKey.F17:
            return "f17";
        case iohook.UiohookKey.F18:
            return "f18";
        case iohook.UiohookKey.F19:
            return "f19";
        case iohook.UiohookKey.F20:
            return "f20";
        case iohook.UiohookKey.F21:
            return "f21";
        case iohook.UiohookKey.F22:
            return "f22";
        case iohook.UiohookKey.F23:
            return "f23";
        case iohook.UiohookKey.F24:
            return "f24";
        case iohook.UiohookKey.Semicolon:
            return ";";
        case iohook.UiohookKey.Equal:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.Comma:
            return ",";
        case iohook.UiohookKey.Minus:
            return "-";
        case iohook.UiohookKey.Period:
            return ".";
        case iohook.UiohookKey.Slash:
            return "/";
        case iohook.UiohookKey.Backquote:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.BracketLeft:
            return "[";
        case iohook.UiohookKey.Backslash:
            return "\\";
        case iohook.UiohookKey.BracketRight:
            return "]";
        case iohook.UiohookKey.Quote:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.Ctrl:
            return "ctrl";
        case iohook.UiohookKey.CtrlRight:
            return "ctrl";
        case iohook.UiohookKey.Alt:
            return "alt";
        case iohook.UiohookKey.AltRight:
            return "alt";
        case iohook.UiohookKey.Shift:
            return "shift";
        case iohook.UiohookKey.ShiftRight:
            return "shift";
        case iohook.UiohookKey.Meta:
            return "meta";
        case iohook.UiohookKey.MetaRight:
            return "meta";
        case iohook.UiohookKey.NumLock:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.ScrollLock:
            return UNSUPPORTED_KEY;
        case iohook.UiohookKey.PrintScreen:
            return UNSUPPORTED_KEY;
    }
    return UNSUPPORTED_KEY;
}
